In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

Reading data from csv

In [9]:
ds = pd.read_csv('sample-iris.csv')
X = ds.drop('Species', axis=1)
y = ds['Species']

trainX, testX, trainY, testY = train_test_split(X, y, test_size=.3, random_state=0)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
60    61            5.0           2.0            3.5           1.0
116  117            6.5           3.0            5.5           1.8
144  145            6.7           3.3            5.7           2.5
119  120            6.0           2.2            5.0           1.5
108  109            6.7           2.5            5.8           1.8
..   ...            ...           ...            ...           ...
9     10            4.9           3.1            1.5           0.1
103  104            6.3           2.9            5.6           1.8
67    68            5.8           2.7            4.1           1.0
117  118            7.7           3.8            6.7           2.2
47    48            4.6           3.2            1.4           0.2

[105 rows x 5 columns]

Training model

In [11]:
classifier = DecisionTreeClassifier()
classifier.fit(trainX, trainY)

DecisionTreeClassifier()

Checking prediction

In [13]:
predY = classifier.predict(testX)
print("Confusion matrix : ")
print(metrics.confusion_matrix(testY, predY))

print("Accuracy Score : ")
print(metrics.accuracy_score(testY, predY))

print("Classification report : ")
print(metrics.classification_report(testY, predY))

Confusion matrix : 
[[16  0  0]
 [ 0 18  0]
 [ 0  1 10]]
Accuracy Score : 
0.9777777777777777
Classification report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.95      1.00      0.97        18
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.98        45
   weighted avg       0.98      0.98      0.98        45

